name 'prachetasp-phantomjs'
version '0.0.1'
source 'https://github.com/prachetasp/puppet-phantomjs'
author 'prachetasp'
license 'MIT License'
summary 'Simple puppet module that installs PhantomJS - headless WebKit scriptable with a Javascript API. Released under prachetasp till merged with 3fs original module'
description 'Simple puppet module that installs PhantomJS - headless WebKit scriptable with a Javascript API. Released under prachetasp till merged with 3fs original module'
project_page 'https://github.com/prachetasp/puppet-phantomjs'
